### PR TITLE
nshlib: Reuse nsh_session logic in nsh_telnetmain

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
to avoid the code duplication

## Impact
Code refactor only

## Testing
Test with sim:adb(https://github.com/apache/incubator-nuttx/pull/7332)

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@masayuki2009 could you review this patch? This is the first patch to reconstruct telnetd after your change: https://github.com/apache/incubator-nuttx-apps/pull/1254.

**Review by masayuki2009 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Ok, I will take a look in the weekend.

**Comment by xiaoxiang781216** [comment]
@hartmannathan I try telnetd with sim:adb(https://github.com/apache/nuttx/pull/8572), all look good:
```
telnet 127.0.0.1 2323
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.

Welcome to NuttShell(NSH) Telnet Server...
login: admin
password: Administrator

User Logged-in!

NuttShell (NSH) NuttX-12.0.0
nsh> ps
ps
  PID GROUP PRI POLICY   TYPE    NPX STATE    EVENT     SIGMASK   STACK COMMAND
    0     0   0 FIFO     Kthread N-- Ready              00000000 066512 Idle Task
    1     1 255 FIFO     Kthread --- Waiting  Signal    00000000 067504 loop_task
    2     2 224 FIFO     Kthread --- Waiting  Semaphore 00000000 067488 hpwork 0x559dbf7b4300
    3     3 100 FIFO     Kthread --- Waiting  Semaphore 00000000 067488 lpwork 0x559dbf7b4340
    4     4 100 FIFO     Task    --- Waiting  Semaphore 00000000 067504 nsh_main
    5     5 100 FIFO     Task    --- Waiting  Semaphore 00000010 067504 telnetd
    6     6 100 FIFO     Task    --- Running            00000010 068528 Telnet session
nsh> 
```

**Comment by hartmannathan** [comment]
Thanks for looking. I wonder if something is different when running in sim vs when running on hardware. In my builds, I have been reverting this commit to get a working nsh/telnet. Maybe something has changed in the last few days, so I will try again and let you know...

**Pull request merged**
