### PR TITLE
[BACKPORT #439] Update gs2200m daemon

### PR DESCRIPTION
**Pull request by btashton**
## Summary
Backport of #439

    This PR updates the gs2200m daemon and consists of the following 4 commits
    commit 1: wireless: gs2200m: Fix to handle UDP connect() with bind()
        This commit fixes to handle UDP connect() with bind() to local port
        NOTE: GS2200M does not support TCP connect() with bind to local port
    commit 2: wireless: gs2200m: Fix to handle address info in accept()
        This commit fixes to handle address info in accept()
    commit 3: wireless: gs2200m: Implement getpeername_request()
        This commit adds getperrname_request() to gs2200m_main.c
    commit 4: wireless: gs2200m: Add support for ioctl(fd, SIOCGIFADDR, ...)
        This commit adds support for ioctl(fd, SIOCGIFADDR, ...) to gs2200m_main.c

### CODE REVIEW

**Comment by btashton** [comment]
This wont pass until some OS backports are in.

**Comment by btashton** [comment]
I'll rebase this once https://github.com/apache/incubator-nuttx/pull/2171 passes and is merged as I think it requires that.

**Comment by Ouss4** [comment]
I merged that kernel PR but I don't think that was the issue. It's only macOS failing.  Anyway, let's try again...

**Comment by btashton** [comment]
I need to rebase it

**Pull request merged**
