### PR TITLE
build: Support both .s & .S

### PR DESCRIPTION
**Pull request by no1wudi**
## Summary
See title

## Impact
None
## Testing
Tested on stm32

### CODE REVIEW

**Comment by patacongo** [comment]
By convention, .s and .S files are normally different file types.  .s is raw assembly code; .S files need to be run through the C pre-processor before being assembled.  .s files are assembled with an assembler like as; .S files are assembled with the compile such as gcc.  We need to support both .s and .S files, not one or the other.

**Comment by no1wudi** [comment]
> By convention, .s and .S files are normally different file types. .s is raw assembly code; .S files need to be run through the C pre-processor before being assembled. .s files are assembled with an assembler like as; .S files are assembled with the compile such as gcc. We need to support both .s and .S files, not one or the other.

Both .s & .S supported now, 
I pass the .s file to gcc as .S, is there any problem ?

**Comment by no1wudi** [comment]
The build break is from sim/up_tapdev.c

**Comment by xiaoxiang781216** [comment]
Fix here: https://github.com/apache/incubator-nuttx/pull/1743

**Comment by xiaoxiang781216** [comment]
> By convention, .s and .S files are normally different file types. .s is raw assembly code; .S files need to be run through the C pre-processor before being assembled. .s files are assembled with an assembler like as; .S files are assembled with the compile such as gcc.

Two issues here:
1.Toolchain.defs doesn't define assembler related macro(e.g. AS, ASFLAGS...).
2.There is no huge side effect that let *.s also pass through the preprocess.

> We need to support both .s and .S files, not one or the other.

How about we add a new .s rule but has the same action as .S?

**Comment by no1wudi** [comment]
> > By convention, .s and .S files are normally different file types. .s is raw assembly code; .S files need to be run through the C pre-processor before being assembled. .s files are assembled with an assembler like as; .S files are assembled with the compile such as gcc.
> 
> Two issues here:
> 1.Toolchain.defs doesn't define assembler related macros(e.g. AS, ASFLAGS...).
> 2.There is no huge side effect that let *.s also pass through the preprocess.
> 
> > We need to support both .s and .S files, not one or the other.
> 
> How about we add a new .s rule but has the same action as .S?

In fact, asm in apps side is less common, I think it's ok otherwise the symbol in raw assembly code (.s) is dulpicated with existing pre-processor's definition

**Comment by xiaoxiang781216** [comment]
@patacongo do you have more comment with the new approach?

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
