### PR TITLE
Bump LVGL version to latest release

### PR DESCRIPTION
**Pull request by no1wudi**
### LVGL

Bump version to 7.0.2, most Kconfig options are compatible, with a few new options.

### LVGL Demo

* Migrate touch calibrate programs to v7.

* Previous demo are deprecated by upstream,  now we download lv_examples tarball from GitHub like LVGL library.

## Impact

No impact for most boards, but imxrt1060-evk's lvgl defconfig contains some deprecated configs,
may make ci problems.

See https://github.com/apache/incubator-nuttx/pull/1261

## Testing
Tested on stm32f429i-disco

### CODE REVIEW

**Comment by acassis** [comment]
Hi Huang Qi (@no1wudi) the issue appears on the build system not in the source code. Could you please check?

**Comment by acassis** [comment]
Ok, I restarted the workflow let to see if it will work now.

**Comment by no1wudi** [comment]
> Ok, I restarted the workflow let to see if it will work now.

**Comment by no1wudi** [comment]
> Ok, I restarted the workflow let to see if it will work now

It seems the error occurred here:
>2020-06-17T12:53:32.5126480Z   Normalize imxrt1060-evk/lvgl
>2020-06-17T12:53:33.2381085Z 23d22
>2020-06-17T12:53:33.2381553Z < CONFIG_EXAMPLES_LVGLDEMO_THEME_2=y
>2020-06-17T12:53:33.2381698Z 47,48d45
>2020-06-17T12:53:33.2381840Z < CONFIG_LV_USE_THEME_ALIEN=y
>2020-06-17T12:53:33.2381953Z < CONFIG_LV_USE_THEME_DEFAULT=y
>2020-06-17T12:53:33.2382076Z 51,52d47
>2020-06-17T12:53:33.2382201Z < CONFIG_LV_USE_THEME_NEMO=y
>2020-06-17T12:53:33.2382328Z < CONFIG_LV_USE_THEME_NIGHT=y
>2020-06-17T12:53:33.2382451Z 54d48
>2020-06-17T12:53:33.2382572Z < CONFIG_LV_USE_THEME_ZEN=y

**Comment by patacongo** [comment]
> 
> 
> > Ok, I restarted the workflow let to see if it will work now
> 
> It seems the error occurred here:
> 
> > 2020-06-17T12:53:32.5126480Z   Normalize imxrt1060-evk/lvgl
> > 2020-06-17T12:53:33.2381085Z 23d22
> > 2020-06-17T12:53:33.2381553Z < CONFIG_EXAMPLES_LVGLDEMO_THEME_2=y
> > 2020-06-17T12:53:33.2381698Z 47,48d45
> > 2020-06-17T12:53:33.2381840Z < CONFIG_LV_USE_THEME_ALIEN=y
> > 2020-06-17T12:53:33.2381953Z < CONFIG_LV_USE_THEME_DEFAULT=y
> > 2020-06-17T12:53:33.2382076Z 51,52d47
> > 2020-06-17T12:53:33.2382201Z < CONFIG_LV_USE_THEME_NEMO=y
> > 2020-06-17T12:53:33.2382328Z < CONFIG_LV_USE_THEME_NIGHT=y
> > 2020-06-17T12:53:33.2382451Z 54d48
> > 2020-06-17T12:53:33.2382572Z < CONFIG_LV_USE_THEME_ZEN=y
> 
> But no error or warning in my local build for this board.

Yes, you will need to update ALL defconfig files under boards/

    find boards -name defconfig

And each of these configurations will have to go through tools/refresh.sh

    tools/refresh.sh --silent

Then commit and push the result to your branch.

**Comment by no1wudi** [comment]
> > > Ok, I restarted the workflow let to see if it will work now
> > 
> > 
> > It seems the error occurred here:
> > > 2020-06-17T12:53:32.5126480Z   Normalize imxrt1060-evk/lvgl
> > > 2020-06-17T12:53:33.2381085Z 23d22
> > > 2020-06-17T12:53:33.2381553Z < CONFIG_EXAMPLES_LVGLDEMO_THEME_2=y
> > > 2020-06-17T12:53:33.2381698Z 47,48d45
> > > 2020-06-17T12:53:33.2381840Z < CONFIG_LV_USE_THEME_ALIEN=y
> > > 2020-06-17T12:53:33.2381953Z < CONFIG_LV_USE_THEME_DEFAULT=y
> > > 2020-06-17T12:53:33.2382076Z 51,52d47
> > > 2020-06-17T12:53:33.2382201Z < CONFIG_LV_USE_THEME_NEMO=y
> > > 2020-06-17T12:53:33.2382328Z < CONFIG_LV_USE_THEME_NIGHT=y
> > > 2020-06-17T12:53:33.2382451Z 54d48
> > > 2020-06-17T12:53:33.2382572Z < CONFIG_LV_USE_THEME_ZEN=y
> > 
> > 
> > But no error or warning in my local build for this board.
> 
> Yes, you will need to update ALL defconfig files under boards/
> 
> ```
> find boards -name defconfig | xargs grep -l LVGL
> ```
> 
> And each of these configurations will have to go through tools/refresh.sh
> 
> ```
> tools/refresh.sh --silent
> ```
> 
> Then commit and push the result to your branch.

Thanks, only four board has lvgl related defconfig, and only this board use these options,
I fixed it manually, the ci flow should pass all check now.

**Pull request merged**
