### PR TITLE
testing/ostest:  Add a test of the getopt() family of interfaces.

### PR DESCRIPTION
**Pull request by patacongo**
## Summary

This new test was used to verify the new implementations of getopt_long() and getopt_long_only() and to verify that there are no regressions to the existing getopts().  See #apache/incubator-nuttx/3272

## Impact

Only the OS test is affect by this change.

## Testing

Verified with the getopt() modifications on a modified version of the sim:nsh configuration.

### CODE REVIEW

**Comment by patacongo** [comment]
This test will fail until #apache/incubator-nuttx/3272 is merged.  In includes testing of the new interfaces getopt_long() and getopt_long_only() that are added by that PR.  I will need to wait for 3272 to be merged and then rebase.  It does compile without error when all the interfaces are available.

**Review by xiaoxiang781216 — APPROVED** [review]
LGTM.

**Comment by xiaoxiang781216** [comment]
@patacongo the patch has nxstyle warning need to be resolved.

**Comment by patacongo** [comment]
> @patacongo the patch has nxstyle warning need to be resolved.

Fixed.  Thanks.

**Comment by masayuki2009** [comment]
Hmm, esp32-devkitc:smp ostest failed.

user_main: getopt() test
getopt():  Simple test
xtensa_user_panic: User Exception: EXCCAUSE=001c task: ostest
xtensa_dumpstate: CPU0:
xtensa_registerdump:    PC: 400de2fb    PS: 00060f30
xtensa_registerdump:    A0: 800de06d    A1: 3ffec050    A2: 0000003f    A3: 3ffec140
xtensa_registerdump:    A4: 3f402645    A5: 00000000    A6: 00000000    A7: 3ffec260
xtensa_registerdump:    A8: 800da084    A9: 00000000   A10: 0000002d   A11: 0000000a
xtensa_registerdump:   A12: 3ffe9e90   A13: 00060d20   A14: 0000000c   A15: 3ffec0b0
xtensa_registerdump:   SAR: 00000020 CAUSE: 0000001c VADDR: 800da084
xtensa_registerdump:  LBEG: 4000c2e0  LEND: 4000c2f6  LCNT: 00000000
xtensa_registerdump:  TMP0: 400807da  TMP1: 3ffebe30
xtensa_btdump: Backtrace0: 400d4933:3ffebdd0
xtensa_btdump: Backtrace1: 400d4a41:3ffebdf0
xtensa_btdump: Backtrace2: 400d48c3:3ffebe10
xtensa_btdump: Backtrace3: 400807f4:3ffebe30
xtensa_btdump: Backtrace4: 40020:0
xtensa_btdump: BACKTRACE CORRUPTED!
xtensa_dumpstate: sp:         3ffebd80
xtensa_dumpstate: stack base: 3ffec220
xtensa_dumpstate: stack size: 00002000

**Comment by masayuki2009** [comment]
>Hmm, esp32-devkitc:smp (QEMU) ostest failed.

The ostest with spresense:smp also failed.

Finally, I found that the task-specific data is not initialized.
I will create a new PR later.

**Pull request merged**
