### PR TITLE
webclient: use getaddrinfo to get IPv4 addresses on dual stack systems

### PR DESCRIPTION
**Pull request by juniskane**
Also wget state is now allocated in order to conserve stack space.

### CODE REVIEW

**Comment by juniskane** [comment]
Build is failing because of this? I can't see any other reason:

  CC       frontends/conf/frontends_conf_kconfig_conf-conf.o
frontends/conf/conf.c:78:10: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
                printf(_("aborted!\n\n"));
                       ^~~~~~~~~~~~~~~~~
./libs/parser/lkc.h:34:17: note: expanded from macro '_'
#define _(text) gettext(text)
                ^~~~~~~~~~~~~
frontends/conf/conf.c:78:10: note: treat the string as an argument to avoid this
                printf(_("aborted!\n\n"));
                       ^
                       "%s", 
./libs/parser/lkc.h:34:17: note: expanded from macro '_'
#define _(text) gettext(text)
                ^
frontends/conf/conf.c:79:10: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
                printf(_("Console input/output is redirected. "));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./libs/parser/lkc.h:34:17: note: expanded from macro '_'

Also, can we make the style checks optional please?

**Comment by xiaoxiang781216** [comment]
> Build is failing because of this? I can't see any other reason:

Because this commit enforce the repo must in clean state after make distclean:
https://github.com/apache/incubator-nuttx-apps/commit/989988fa7203ab5e5d26b140c8a43ddeb41d578e
But the current mainline doesn't fix all issue yet. I will provide a patch temporarily until we clean up the code base.

> 
> CC frontends/conf/frontends_conf_kconfig_conf-conf.o
> frontends/conf/conf.c:78:10: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
> printf(_("aborted!\n\n")); ^~~~~~~~~~~~~~~~~ ./libs/parser/lkc.h:34:17: note: expanded from macro '_'
> #define _(text) gettext(text) ^~~~~~~~~~~~~ frontends/conf/conf.c:78:10: note: treat the string as an argument to avoid this printf(_("aborted!\n\n"));
> ^
> "%s",
> ./libs/parser/lkc.h:34:17: note: expanded from macro '_' #define _(text) gettext(text) ^ frontends/conf/conf.c:79:10: warning: format string is not a string literal (potentially insecure) [-Wformat-security] printf(_("Console input/output is redirected. ")); ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ./libs/parser/lkc.h:34:17: note: expanded from macro '_'

**Comment by xiaoxiang781216** [comment]
Here is the PR: https://github.com/apache/incubator-nuttx-apps/pull/198

**Comment by patacongo** [comment]
> Here is the PR: #198

That is this PR????

I just restarted the PR checks for the 3rd time and it is still failing as it was before.

**Comment by Ouss4** [comment]
It's #199 actually. I also restarted the checks when I merged it.  I guess this PR needs to be rebased.

**Comment by gregory-nutt** [comment]
> 
> 
> It's #199 actually. I also restarted the checks when I merged it. I guess this PR needs to be rebased.

We can rebase the branch for Juha, right?  I tried but I am not sure how to do that.

**Comment by Ouss4** [comment]
We can if he wants to.  That would require force pushing.

**Comment by xiaoxiang781216** [comment]
Yes, the ci check still run on the base when PR submit. @juniskane could you rebase your PR to the latest mainline?

**Comment by xiaoxiang781216** [comment]
> > It's #199 actually. I also restarted the checks when I merged it. I guess this PR needs to be rebased.
> 
> We can rebase the branch for Juha, right? I tried but I am not sure how to do that.

Here has the info:
https://github.blog/2016-09-07-improving-collaboration-with-forks/
Basically, you have to clone(remote add) the contributor's repo, modify the patch and push to his repo.

**Comment by juniskane** [comment]
Done rebase + force push. Feel free to take this or similar actions for my branches in the future if I'm absent. I consider my PR branches ephemeral. But now the CI is failing due to Internal Error 500 *sigh*

**Comment by xiaoxiang781216** [comment]
github is unstable again:(. We have to rerun it from Checks tab.

**Comment by patacongo** [comment]
> But now the CI is failing due to Internal Error 500 _sigh_

I've re-started it a few time, but it is still randomly failing.

**Pull request merged**
