### PR TITLE
nshlib: Fix the build break in nsh_telnetd.c when CONFIG_NSH_CONSOLE=n

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

by moving the intializition code to nsh_telnetmain.
Note: the init script postpone the execution when the first user login too.

## Impact

See the issue description:
https://github.com/apache/incubator-nuttx-apps/issues/584

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@lukegluke please try this path.

**Comment by lukegluke** [comment]
Hi @xiaoxiang781216,
Patch fixed the build, but network not works if CONFIG_NSH_CONSOLE=n.
I suppose it is because netinit_bringup() is called only from nsh_consolemain (usbconsole/altconsole):
https://github.com/apache/incubator-nuttx-apps/blob/39a1950098b331c5a2c203431ffc26f276274863/nshlib/nsh_consolemain.c#L101-L105
that in turn is not called if no console:
https://github.com/apache/incubator-nuttx-apps/blob/f613da4f92d5ae1f719cda3f3f2ae28db3b7559b/system/nsh/nsh_main.c#L165-L168

**Comment by acassis** [comment]
@lukegluke about #584 do you know which PR broke it? Maybe we could revert the offending PR until we have telnet working with it again.

**Comment by lukegluke** [comment]
@acassis I had found it by git blame for that time, but I can't say it to you now.
Why not just moved netinit_bringup() code to main(int argc, FAR char *argv[]) in nsh_main.c (see code parts above)?

**Comment by acassis** [comment]
> @acassis I had found it by git blame for that time, but I can't say it to you now.
> Why not just moved netinit_bringup() code to main(int argc, FAR char *argv[]) in nsh_main.c (see code parts above)?

Because netinit_bringup() doesn't depend on nsh! You can create a standalone (a modified hello_world for example) that needs network initialization.

**Comment by lukegluke** [comment]
Yes you're right, I see. But as it seemed to me that previously netinit_bringup was also in nsh, so it is another problem. I didn't get deep into history of this issue and related net bringup problems, just noticed the issue.

**Comment by xiaoxiang781216** [comment]
See the better fix here: https://github.com/apache/incubator-nuttx-apps/pull/703

**Pull request closed without merging**
