### PR TITLE
CI: build arm-11 instead of arm-13 for macOS

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
to reduce the building time from ~50m to ~30m

Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>

### CODE REVIEW

**Comment by yamt** [comment]
i chose arm-13 because it detected https://github.com/apache/incubator-nuttx-apps/pull/156
do you know why arm-11 is quicker than arm-13?

**Comment by xiaoxiang781216** [comment]
> i chose arm-13 because it detected #156
> do you know why arm-11 is quicker than arm-13?

Because arm-11 take 17m to finish on Ubuntu but arm-13 take 20m.

**Comment by yamt** [comment]
17m vs 20m seems far less drastic than ~30m vs ~50m. i wonder why.
i suspect 30m vs 50m involves cache miss/hit differences.
see also: https://github.com/actions/cache/issues/208

**Comment by yamt** [comment]
can you give me the link to the log of 50m?

**Comment by xiaoxiang781216** [comment]
> can you give me the link to the log of 50m?

https://github.com/apache/incubator-nuttx/pull/772/checks?check_run_id=583218421

**Comment by yamt** [comment]
thank you.
i looked at the log. but i didn't notice anything obvious.
maybe the processing speed simply varies in the environment.
in the mean time, i'm fine with this patch.

**Pull request merged**
