### PR TITLE
Update LVGL to latest release

### PR DESCRIPTION
**Pull request by no1wudi**
No need for lv_symbol_def.patch now, but  system still check the lv_symbol_def.h cause this error

How to resolve it?

### CODE REVIEW

**Comment by acassis** [comment]
Hi no1wudi,
Do you know why it is reporting this error in the CI:
 lvgl.fix/lv_misc/lv_symbol_def.h: fatal: Failed to open
lvgl.fix/lv_misc/lv_symbol_def.h: fatal: Failed to open
##[error]Process completed with exit code 1.

**Comment by xiaoxiang781216** [comment]
> Hi no1wudi,
> Do you know why it is reporting this error in the CI:
> lvgl.fix/lv_misc/lv_symbol_def.h: fatal: Failed to open
> lvgl.fix/lv_misc/lv_symbol_def.h: fatal: Failed to open
> ##[error]Process completed with exit code 1.

I think in the new version, this patch doesn't need anymore. @no1wudi provide a patch fix this.

**Comment by xiaoxiang781216** [comment]
> > Hi no1wudi,
> > Do you know why it is reporting this error in the CI:
> > lvgl.fix/lv_misc/lv_symbol_def.h: fatal: Failed to open
> > lvgl.fix/lv_misc/lv_symbol_def.h: fatal: Failed to open
> > ##[error]Process completed with exit code 1.
> 
> I think in the new version, this patch doesn't need anymore. @no1wudi please provide a patch fix this.

seems like already fix by:
https://github.com/apache/incubator-nuttx-apps/pull/179/commits/b3be003660277e1866118df298c0124283f158d2

**Comment by acassis** [comment]
Ok, so I will merge it.

**Comment by xiaoxiang781216** [comment]
> Ok, so I will merge it.

No! but it's not really fix it. It seems like cibuild.sh issue, not this PR.

**Comment by xiaoxiang781216** [comment]
> > Ok, so I will merge it.
> 
> No! but it's not really fix it. It seems like cibuild.sh issue, not this PR.

@liuguo09 will take a look, bu anyway PR is right and shouldn't introduce other build break.

**Pull request merged**
