### PR TITLE
Fix multi MAINSRC match suffix in single Makefile

### PR DESCRIPTION
**Pull request by Donny9**
## Summary
Fix multi MAINSRC match suffix in single Makefile 

## Impact
We can compile multi program in single makefile with different suffix file in MAINSRC.
eg: MAINSRC = xxx1.c
      PROGNAME = xxx1
      MAINSRC += xxx2.cpp
      RROGNAME += xxx2

## Testing
Built locally

### CODE REVIEW

**Comment by v01d** [comment]
This feels conceptually wrong, why would need two main files? There should be only a single entry function, regardless of C vs C++ (which is currently supported). If there are two "main" this are two separate applications. An app with two mains does not exist in other OSs.

**Comment by Donny9** [comment]
> This feels conceptually wrong, why would need two main files? There should be only a single entry function, regardless of C vs C++ (which is currently supported). If there are two "main" this are two separate applications. An app with two mains does not exist in other OSs.

Hello @v01d ,you can see following makefile about zmode, it use double main file.
https://github.com/apache/incubator-nuttx-apps/blob/master/system/zmodem/Makefile

**Comment by v01d** [comment]
I'm not sure I follow how that works or why is designed that way.

**Comment by v01d** [comment]
Ah, I see there are two PROGNAME. Well, I can't say I like the idea. In any other OS you would have to different applications built separately sharing common code via a library. This is actually possible in NuttX, it only takes more work. Anyway, I understand you are simple allowing different languages for each main.
I can approve the change, even if I don't really like the idea (which is independent of this PR)

**Review by v01d — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@v01d should we merge this PR? We can create a new issue to track the problem of application structure.

**Comment by v01d** [comment]
Yes, I approved, you can merge if you agree as well.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Ok, let's go ahead.

**Pull request merged**
