### PR TITLE
CI: Migrate ci tooling from testing repository to main os repo

### PR DESCRIPTION
**Pull request by btashton**
## Summary
This is the app half off https://github.com/apache/incubator-nuttx/pull/3318
CI tooling and docker container is now in the os repo.

## Testing
CI should build.

### CODE REVIEW

**Comment by btashton** [comment]
This build will need to be retried once the OS side is merged.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@btashton I have trigger several time, but ci still fail.

**Comment by btashton** [comment]
> @btashton I have trigger several time, but ci still fail.

@xiaoxiang781216 looked like what was running did not have the os side merged yet, but now the sha looks good and I see at least 2 of the Linux jobs running builds now.

**Comment by xiaoxiang781216** [comment]
@btashton "Lint / 🍺 YAML (pull_request)"(apps) is different from "Lint / Lint (pull_request)"(nuttx).

**Comment by btashton** [comment]
Yes I'll update that in another PR when we enable the python linting.

**Comment by xiaoxiang781216** [comment]
Ok.

**Pull request merged**
