### PR TITLE
Revert "Minor fixes"

### PR DESCRIPTION
**Pull request by pkarashchenko**
Reverts apache/incubator-nuttx-apps#1377

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@pkarashchenko why revert the change?

**Comment by pkarashchenko** [comment]
> @pkarashchenko why revert the change?

I made a mistake in one commit and CI on mainline failed because of that. I did revert because will not have time till evening to fix the broken commit, so just to unblock others.

**Comment by pkarashchenko** [comment]
Let's try to fix compilation failure when GCC can't find `#include <array>`, so we can have reliable feedback from CI.

**Comment by xiaoxiang781216** [comment]
> > @pkarashchenko why revert the change?
> 
> I made a mistake in one commit and CI on mainline failed because of that. I did revert because will not have time till evening to fix the broken commit, so just to unblock others.

which patch? I don't see your change can trigger `#include <array>` error.

**Comment by pkarashchenko** [comment]
> > > @pkarashchenko why revert the change?
> > 
> > I made a mistake in one commit and CI on mainline failed because of that. I did revert because will not have time till evening to fix the broken commit, so just to unblock others.
> 
> which patch? I don't see your change can trigger `#include <array>` error.

https://github.com/apache/incubator-nuttx-apps/actions/runs/3304553082/jobs/5454071840#step:7:1

**Comment by xiaoxiang781216** [comment]
Here is the fix for `#incude <array>`: https://github.com/apache/incubator-nuttx-apps/pull/1379, not your change @pkarashchenko .

**Comment by pkarashchenko** [comment]
> Here is the fix for `#incude <array>`: https://github.com/apache/incubator-nuttx-apps/pull/1379, not your change @pkarashchenko .

Yes. Thank you. My changes still have an issue that was not caught by CI due to array issue. I will resubmit my change later today

**Pull request merged**
