### PR TITLE
examples: Fix the parallel build break

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
1.Remove build target to avoid build and install run parallelly
2.Invoke the sub Makefile just before the parent source code compile

Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@masayuki2009 @patacongo this PR can fix the parallel build break, please merge it.

**Comment by patacongo** [comment]
> @patacongo this PR can fix the parallel build break, please merge it.

Yes, of course.  I don't normally merge build system changes only because I don't understand them completely.

**Comment by masayuki2009** [comment]
> @masayuki2009 @patacongo this PR can fix the parallel build break, please merge it.

@xiaoxiang781216 
Hmm, I've just tried parallel-build-aging.sh which I did before but it failed.
Anway, let's see what will happen at today's nightly build.

```
make[4]: Entering directory '/mnt/m2ssd/opensource/github_masayuki2009/apache-nuttx-sync/apps/examples/elf/tests/helloxx'
LD: hello++1.o
riscv64-unknown-elf-ld: hello++1.o: file not recognized: file truncated
Makefile:126: recipe for target 'hello++1' failed
make[4]: *** [hello++1] Error 1
make[4]: Leaving directory '/mnt/m2ssd/opensource/github_masayuki2009/apache-nuttx-sync/apps/examples/elf/tests/helloxx'
Makefile:86: recipe for target 'helloxx_install' failed
make[3]: *** [helloxx_install] Error 2
make[3]: Leaving directory '/mnt/m2ssd/opensource/github_masayuki2009/apache-nuttx-sync/apps/examples/elf/tests'
Makefile:59: recipe for target 'build' failed
make[2]: *** [build] Error 2
make[2]: Leaving directory '/mnt/m2ssd/opensource/github_masayuki2009/apache-nuttx-sync/apps/examples/elf'
CC:  environ/env_removevar.c
Makefile:64: recipe for target '/mnt/m2ssd/opensource/github_masayuki2009/apache-nuttx-sync/apps/examples/elf_all' failed
make[1]: *** [/mnt/m2ssd/opensource/github_masayuki2009/apache-nuttx-sync/apps/examples/elf_all] Error 2
make[1]: Leaving directory '/mnt/m2ssd/opensource/github_masayuki2009/apache-nuttx-sync/apps'
```

**Comment by xiaoxiang781216** [comment]
> > @masayuki2009 @patacongo this PR can fix the parallel build break, please merge it.
> 
> @xiaoxiang781216
> Hmm, I've just tried parallel-build-aging.sh which I did before but it failed.
> Anway, let's see what will happen at today's nightly build.
> 

Yes, there are other place has the similar issue need to fix too.

**Comment by masayuki2009** [comment]
> > > @masayuki2009 @patacongo this PR can fix the parallel build break, please merge it.
> > 
> > 
> > @xiaoxiang781216
> > Hmm, I've just tried parallel-build-aging.sh which I did before but it failed.
> > Anway, let's see what will happen at today's nightly build.
> 
> The key fix is avoid invoke sub Makefile parallelly, like below:
> image
> Because populate depends on build and install, build and install will run concurrently in parallel build, then the same object file may be written by multiple thread at the same time.
> There are other place has the similar issue we need to find and fix.

@xiaoxiang781216 
Hmm, however, it seems that the latest build results (https://builds.apache.org/job/NuttX-Nightly-Build/74/consoleText) show many errors (not only link errors) in the following targets
samv71-xult/module, lc823450-xgevk/elf, lc823450-xgevk/posix_spawn, stm32f4discovery/elf,
spresense/elf, maix-bit/elf, maix-bit/posix_spawn and maix-bit/module.

In my understanding, the above targets were going to be built correctly by this PR.
However, the results show worse than before.

**Comment by xiaoxiang781216** [comment]
> > Because populate depends on build and install, build and install will run concurrently in parallel build, then the same object file may be written by multiple thread at the same time.
> > There are other place has the similar issue we need to find and fix.
> 
> @xiaoxiang781216
> Hmm, however, it seems that the latest build results (https://builds.apache.org/job/NuttX-Nightly-Build/74/consoleText) show many errors (not only link errors) in the following targets
> samv71-xult/module, lc823450-xgevk/elf, lc823450-xgevk/posix_spawn, stm32f4discovery/elf,
> spresense/elf, maix-bit/elf, maix-bit/posix_spawn and maix-bit/module.
> 
> In my understanding, the above targets were going to be built correctly by this PR.
> However, the results show worse than before.

The high level Makefile likely inovke examples/elf/Makefile.. for different targets concurrently. We need fix other location too, with this command:
make -j8 --debug=basic V=1
We need review the log to fix the location wich trigger the same file compile multiple.

**Pull request merged**
