### PR TITLE
ntpc: optimize stack used

### PR DESCRIPTION
**Pull request by Donny9**
## Summary
ntpc: optimize stack used, this pr is related to https://github.com/apache/incubator-nuttx/pull/5159.

Signed-off-by: Jiuzhu Dong <dongjiuzhu1@xiaomi.com>
## Impact
reduce stack used
## Testing
local compile

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by masayuki2009** [comment]
@Donny9 

I confirmed this PR with spresense:wifi.
Actually, it consumed less memory (2332 bytes) than the latest upstream (3052 bytes).
However, I think we need to modify the default NETUTILS_NTPCLIENT_STACKSIZE as well.

```
   14    14 100 RR       Task    --- Waiting  Signal    00000000 004024 002332  57.9%  NTP daemon 0.pool.ntp.org;1.pool.ntp.org;
```

**Comment by Donny9** [comment]
> @Donny9
> 
> I confirmed this PR with spresense:wifi. Actually, it consumed less memory (2332 bytes) than the latest upstream (3052 bytes). However, I think we need to modify the default NETUTILS_NTPCLIENT_STACKSIZE as well.
> 
> ```
>    14    14 100 RR       Task    --- Waiting  Signal    00000000 004024 002332  57.9%  NTP daemon 0.pool.ntp.org;1.pool.ntp.org;
> ```

Please wait a minute, I will continue optimize this stack used.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@masayuki2009 could you try the new change?

**Comment by masayuki2009** [comment]
@Donny9 

The latest commit reduces the stack size.
Thanks for the fix.

```
   14    14 100 RR       Task    --- Waiting  Signal    00000000 001976 001740  88.0%! NTP daemon 0.pool.ntp.org;1.pool.ntp.org;
```

**Review by masayuki2009 — APPROVED** [review]

**Pull request merged**
