### PR TITLE
libuv: Fix queue.h conflict with nuttx verson

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
required by https://github.com/apache/incubator-nuttx/pull/6987

## Impact
Move src/queue.h to include/uv/queue.h to avoid the conflict with nuttx/include/queue.h

## Testing
Pass CI

### CODE REVIEW

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 I think that you need to generate patch with `--no-renames` option to get `patch` correctly interpreted on MAC

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 I think that you need to generate patch with `--no-renames` option to get `patch` correctly interpreted on MAC

Done.

**Comment by xiaoxiang781216** [comment]
@pkarashchenko it's pass ci now, could you merge this patch to unblock https://github.com/apache/incubator-nuttx/pull/6987 and https://github.com/apache/incubator-nuttx/pull/6318.

**Comment by pkarashchenko** [comment]
What about my comment in https://github.com/apache/incubator-nuttx/pull/6987 ? Maybe we can move nuttx specific queue.h instead?

**Comment by xiaoxiang781216** [comment]
Let's close this PR to prefer https://github.com/apache/incubator-nuttx/pull/7185

**Pull request closed without merging**
