### PR TITLE
Avoid calling ARCHIVE in multiple places

### PR DESCRIPTION
**Pull request by yamt**

### CODE REVIEW

**Comment by yamt** [comment]
this way argument list might get too long. if it does, maybe we can do xargs or something like that.

**Comment by xiaoxiang781216** [comment]
Yes, this method should fix the problem too, but I have one concern:
ELF executable can be generated by change y to m, the next step we plan apply the similar approach to dynamic library, then only static object files will package into libapps.a, other dynamic object files will package to individual so.
This modification make this change hard.

**Comment by yamt** [comment]
isn't it a matter to change the output of show-objs target according to BUILD_MODULE?

**Comment by xiaoxiang781216** [comment]
> isn't it a matter to change the output of show-objs target according to BUILD_MODULE?

Yes, it should be. I am fine with both approach.

**Comment by yamt** [comment]
@xiaoxiang781216 do you know why the default LDLIBS has libapps.a? i don't understand how it's supposed to work.

**Comment by xiaoxiang781216** [comment]
> LDLIBS

LDLIBS is used in nuttx/arch/*/src/Makefile to generate the final binary image. puting libapps.a into LDLIBS ensure the linker can find the symbol from LDLIBS.

**Comment by liuguo09** [comment]
It seems this change result in build break as below. APPOBJS seems not right.

make[2]: Leaving directory '/home/haitao/code/apache/apps/platform'
arm-none-eabi-ar rcs  /home/haitao/code/apache/apps/libapps.a  make[1]: Entering directory '/home/haitao/code/apache/apps' make[2]: Entering directory '/home/haitao/code/apache/apps/nshlib' /home/haitao/code/apache/apps/nshlib/nsh_init.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_parse.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_console.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_script.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_system.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_command.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_fscmds.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_ddcmd.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_proccmds.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_mmcmds.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_timcmds.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_envcmds.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_syscmds.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_dbgcmds.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_session.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_fsutils.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_builtin.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_mntcmds.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_consolemain.home.haitao.code.apache.apps.nshlib.o /home/haitao/code/apache/apps/nshlib/nsh_test.home.haitao.code.apache.apps.nshlib.o make[2]: Leaving directory '/home/haitao/code/apache/apps/nshlib' make[2]: Entering directory '/home/haitao/code/apache/apps/builtin' /home/haitao/code/apache/apps/builtin/builtin_list.home.haitao.code.apache.apps.builtin.o /home/haitao/code/apache/apps/builtin/exec_builtin.home.haitao.code.apache.apps.builtin.o make[2]: Leaving directory '/home/haitao/code/apache/apps/builtin' make[2]: Entering directory '/home/haitao/code/apache/apps/system/readline' /home/haitao/code/apache/apps/system/readline/readline.home.haitao.code.apache.apps.system.readline.o /home/haitao/code/apache/apps/system/readline/readline_common.home.haitao.code.apache.apps.system.readline.o make[2]: Leaving directory '/home/haitao/code/apache/apps/system/readline' make[2]: Entering directory '/home/haitao/code/apache/apps/system/nsh' /home/haitao/code/apache/apps/system/nsh/nsh_main.home.haitao.code.apache.apps.system.nsh.o make[2]: Leaving directory '/home/haitao/code/apache/apps/system/nsh' make[2]: Entering directory '/home/haitao/code/apache/apps/platform' /home/haitao/code/apache/apps/platform/gnu_cxxinitialize.home.haitao.code.apache.apps.platform.o /home/haitao/code/apache/apps/platform/dummy.home.haitao.code.apache.apps.platform.o make[2]: Leaving directory '/home/haitao/code/apache/apps/platform' make[1]: Leaving directory '/home/haitao/code/apache/apps'
arm-none-eabi-ar: make[1]:: No such file or directory
Makefile:118: recipe for target '/home/haitao/code/apache/apps/libapps.a' failed
make[1]: *** [/home/haitao/code/apache/apps/libapps.a] Error 1
make[1]: Leaving directory '/home/haitao/code/apache/apps'
tools/LibTargets.mk:198: recipe for target '../apps/libapps.a' failed
make: *** [../apps/libapps.a] Error 2

**Pull request merged**
