### PR TITLE
examples/lvgldemo: LVGL examples are now called lv_demos and not lv_examples

### PR DESCRIPTION
**Pull request by Ouss4**
## Summary
Change the name of the extracted LVGL examples directory.
## Impact
Fix a current build failure
## Testing
sim:lvgl

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@xiaoxiang781216 and @Ouss4 the LVGL 8.0 was released today. Are you planing to update to the new version?

**Comment by Ouss4** [comment]
> @xiaoxiang781216 and @Ouss4 the LVGL 8.0 was released today. Are you planing to update to the new version?

Not me no.  For this PR I only changed the URL I didn't change the version.  Someone who uses LVGL more frequently and can do proper testing should try to update.

BTW, the relevant CI job has passed (sim-1) the pipeline will still fail due to the missing xtensa-esp32s2 toolchain.  That needs https://github.com/apache/incubator-nuttx/pull/3819  I suggest we merge this one to unblock the rest.

**Comment by xiaoxiang781216** [comment]
> > @xiaoxiang781216 and @Ouss4 the LVGL 8.0 was released today. Are you planing to update to the new version?
> 
> Not me no. For this PR I only changed the URL I didn't change the version. Someone who uses LVGL more frequently and can do proper testing should try to update.
> 

Yes, but it willn't start soon.

> BTW, the relevant CI job has passed (sim-1) the pipeline will still fail due to the missing xtensa-esp32s2 toolchain. That needs [apache/incubator-nuttx#3819](https://github.com/apache/incubator-nuttx/pull/3819) I suggest we merge this one to unblock the rest.

Ok.

**Comment by xiaoxiang781216** [comment]
@Ouss4 the mainline is still broken with this patch.

**Comment by Ouss4** [comment]
> @Ouss4 the mainline is still broken with this patch.

@xiaoxiang781216 is it?  I'm monitoring the jobs of my two open PRs. sim-1 is now passing, I'm waiting for xtensa.

The builds on push to master can't be very reliable now since they run in parallel with the Docker image build.  We'll have to account for the next push to master.

**Pull request merged**
