### PR TITLE
system/sched_note/note_main.c:  Add interrupt/syscall call decode.

### PR DESCRIPTION
**Pull request by patacongo**
## Summary

Add support for decoding interrupt and system call instrumentation

## Impact

None other than to system/sched_note/note_main.c.

## Testing

Tested with sim:nsh

### CODE REVIEW

**Comment by patacongo** [comment]
Merge notes:

1. There are three nxstyle complaints that need to be ignored:

    system/sched_note/note_main.c:609:64: error: Mixed case identifier found
    system/sched_note/note_main.c:653:0: error: No indentation line
    system/sched_note/note_main.c:705:0: error: No indentation line

The first is the use of PRIdPTR from inttypes.h.  The second two make no sense are are, most likely, errors in nxstyle.

2. The PR checks will fail until incubator-nuttx:#1259 is merged.  It depends on a definition added by that PR.

**Comment by jerpelea** [comment]
@ouss4 please add commit messages !

**Comment by Ouss4** [comment]
> @ouss4 please add commit messages !

@jerpelea I'm not quite sure what you mean by that.

**Comment by jerpelea** [comment]
@Ouss4 each commit hshould have a commit title with a short description and a body with an explanation for the commit 

Example:
commit -asm "Short title for my commit 

This is a commit description for my commit explaining why I need to modify the code or what the commit does."

If you run git log in the nuttx git you will see that some commits have just 1 line message (title) while others have several lines a title and a commit message.
This is a best parctice that helps us better document the commits in any project.

**Comment by jerpelea** [comment]
This is another example, from another well known project, how commits look with commit mesages 
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=v5.7.2

**Pull request merged**
