### PR TITLE
webclient: Fix errno in case of recv failure

### PR DESCRIPTION
**Pull request by yamt**
## Summary
webclient: Fix errno in case of recv failure
## Impact
webclient
## Testing
i tested a different version of this code by injecting a failure

### CODE REVIEW

**Comment by jerpelea** [comment]
Please add PR and commit messages !

**Comment by yamt** [comment]
sorry, what do you mean by "Please add PR and commit messages !" ?

**Comment by jerpelea** [comment]
each commit should have a commit message describing the commit and when you create a push request you are asked to fill 3 fields 

"Summary
Impact
Testing"

the commit message for this commit does not describe why the change is needed and there is no information provided in those 3 fields.

**Comment by yamt** [comment]
@jerpelea 
thank you.
i updated the PR description.
i'm not sure what's wrong with the commit message. have you looked at the latest one?

**Comment by jerpelea** [comment]
The commit  message should provide some information why the change is needed or some background.

**Comment by davids5** [comment]
@yamt 

Have a look at 

https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
Or for more more details:

 https://chris.beams.io/posts/git-commit/

Here are some examples of filling in the PR information:

https://github.com/apache/incubator-nuttx/pull/1196
https://github.com/apache/incubator-nuttx/pull/1147

**Comment by yamt** [comment]
are you seriously suggesting we need lengthy explanation for this simple fix?

**Comment by jerpelea** [comment]
@yamt 
Here is how git log looks with and without messages  since some commits were merged without messages.


commit 6f3cef856dda8063245cfdb030c791b7dbf3b163
Author: Xiang Xiao <xiaoxiang@xiaomi.com>
Date:   Mon Jun 8 17:10:52 2020 +0800

    libc: Add the remaining wscanf series declaration

    The function isn't implemented like other wide printf/scanf

    Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>
    Change-Id: I0b26bb5174d1a9295fe2454d0e33f8227b8cbf8a

commit d0158fe8d8324dada35f7f0093ad658ac2663c73
Author: Masayuki Ishikawa <masayuki.ishikawa@gmail.com>
Date:   Mon Jun 8 12:37:54 2020 +0900

    boards: Fix Kconfig for maix-bit with QEMU

    Signed-off-by: Masayuki Ishikawa <Masayuki.Ishikawa@jp.sony.com>

commit 2b0324c3bfe7425a32e8cac846f1d463b46ec507
Author: Huang Qi <huangqi3@xiaomi.com>
Date:   Sat Jun 6 13:18:14 2020 +0800

    boards/risc-v/k210/maix-bit: Add initial autoled support

    Signed-off-by: Huang Qi <huangqi3@xiaomi.com>

commit bcd7ccc0b5392279a159de056779830b57092eb2
Author: Huang Qi <huangqi3@xiaomi.com>
Date:   Sat Jun 6 10:42:33 2020 +0800

    arch/risc-v/src/k210: Add basic gpiohs support

    Signed-off-by: Huang Qi <huangqi3@xiaomi.com>

commit 24262a4ddbccbd33d9020f6e783c94b2ce43cc8c
Author: Xiang Xiao <xiaoxiang@xiaomi.com>
Date:   Sat Jun 6 21:16:53 2020 +0800

    Fix nxstyle issue

    Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>

commit 7a18ebe45980a80370b7afaa4b4d0be703402318
Author: Xiang Xiao <xiaoxiang@xiaomi.com>
Date:   Sat Jun 6 18:35:44 2020 +0800

    drivers/led: Extend userled_set_t from 8bits to 32bits

    Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>
    Change-Id: I5701b42ff930998198b1d915316cc4f2d085d4eb

commit 76965474ac01aaceeb888cfd12c6051fc944906d
Author: Xiang Xiao <xiaoxiang@xiaomi.com>
Date:   Fri Jun 5 18:08:02 2020 +0800

    drivers/led: Let board_userled_initialize return the led number

    so the lower half driver don't need include the specific board.h

    Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>
    Change-Id: Icf6638a6865bac42150b5957376e55909f041d40

**Comment by jerpelea** [comment]
this commit is ok and you can understand what happened in that commit 

"libc: Add the remaining wscanf series declaration

The function isn't implemented like other wide printf/scanf"

this commit is not ok because there is no message (just the title)
"arch/risc-v/src/k210: Add basic gpiohs support"

This one is also slightly wrong because the title sentence was written on 2 lines and the second one became the commit message.

"drivers/led: Let board_userled_initialize return the led number

so the lower half driver don't need include the specific board.h"

**Comment by yamt** [comment]
@jerpelea 
i don't see any obvious problems in the commit log.

anyway, i tried my best to the commit message longer. i hope you like it.

**Comment by jerpelea** [comment]
@yamt Thanks for your patience to fix this minor issue. 

I think that is our job to help other developers on howto do a better documentation on their work so that everybody in the community can understand the changes.

Linux kernel is one of the biggest projects and a good source of inspiration regaring how a commit should be written.
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=v5.7.2

**Comment by yamt** [comment]
@jerpelea 
if it's important for the project, why don't you introduce mechanical enforcement?
i think some projects do something along the line.

(as you might guess, i personally don't love it too much though!)

**Comment by davids5** [comment]
> @jerpelea
> if it's important for the project, why don't you introduce mechanical enforcement?
> i think some projects do something along the line.
> 
> (as you might guess, i personally don't love it too much though!)

Brother - if you only knew how this is a TFE discussion.  Huge changes have been made to the code with no information or worse useless information. Your very well written and detailed explanation will help set an example. THANK YOU for it!

**Comment by yamt** [comment]
@davids5 what's "TFE"?

**Pull request merged**
