### PR TITLE
Initial checkin apps github action CI workflow

### PR DESCRIPTION
**Pull request by liuguo09**
Github action CI workflow steps as below:
1. Checkout apps repo with pull request
2. Checkout nuttx repo since tools/checkpatch.sh must be used
3. Do git commands to get commits in PR and then do checkpatch.sh
4. Checkout testing repo since cibuild.sh must be used later
4. Install build essential tools
5. Call testing/cibuild.sh to do check build

Signed-off-by: liuhaitao <liuhaitao@xiaomi.com>

Not intended to be merged right now. Still need align to check testlist update.

### CODE REVIEW

**Comment by patacongo** [comment]
Does this need an Apache license header?

I know nothing about this and do not feel qualified to do the merge.  I was add @btashton is a reviewer.

**Comment by btashton** [comment]
Let's keep the conversation in the other ticket for now.

**Comment by patacongo** [comment]
Can we close this now?

**Comment by xiaoxiang781216** [comment]
> Can we close this now?

No, Haitao is preparing the final patch.

**Comment by liuguo09** [comment]
It's better close it to ease testing in my fork. I'll reopen the PR ASAP.

**Pull request closed without merging**
