### PR TITLE
examples/oneshot: fixed wrong constant and refactored

### PR DESCRIPTION
**Pull request by saramonteiro**
## Summary
This little PR is intended only to:
* Fix a wrong constant that was being used to convert time unities and 
* Refactor the code using constant definitions instead of raw numbers. 

## Impact
N/A

## Testing
After the changes the maximum delay became correct.

### CODE REVIEW

**Review by davids5 — APPROVED** [review]
LGTM All except but the name of NSEC_PER_USEC seams backwards, doesn't it?

Number for Seconds per micros Second should be NUSEC_PER_SEC, Number for micros Seconds per Second  but that looks like anther PR....

**Comment by v01d** [comment]
> LGTM All except but the name of NSEC_PER_USEC seams backwards, doesn't it?
> 
> Number for Seconds per micros Second should be NUSEC_PER_SEC, Number for micros Seconds per Second but that looks like anther PR....

It refers to nanoseconds per microsecond.

**Comment by saramonteiro** [comment]
> LGTM All except but the name of NSEC_PER_USEC seams backwards, doesn't it?
> 
> Number for Seconds per micros Second should be NUSEC_PER_SEC, Number for micros Seconds per Second but that looks like anther PR....

Hey David, 
these definitions are not mine. They're from `include/nuttx/clock.h` and I don't think it's a good idea to change it.
It will break several files.

**Comment by patacongo** [comment]
> 
> 
> > LGTM All except but the name of NSEC_PER_USEC seams backwards, doesn't it?
> > Number for Seconds per micros Second should be NUSEC_PER_SEC, Number for micros Seconds per Second but that looks like anther PR....
> 
> It refers to nanoseconds per microsecond.

You are interpreting the name incorrectly.  NSEC_PER_USEC does not stand for number seconds per microsecond, it stands for the number nanoseconds per microsecond.  NSEC always refers to nanonseconds in clock.h.

**Pull request merged**
