### PR TITLE
build: Use flock to serialize ar steps as workaround

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
Use flock to serialize ar steps to avoid parallel build break
sometimes.

Change-Id: I3a916b3b27422cdb6d718f7d554361565457fa08
Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
A general version of:
https://github.com/apache/incubator-nuttx/pull/102
Before we get a better solution, this patch can fix the parallel build which is very important for the upcoming Apache Jenkins and Github Action.

**Comment by xiaoxiang781216** [comment]
@masayuki2009 please associate your github account with apache account:
https://whimsy.apache.org/roster/ppmc/nuttx
so I can add you to reviewer list.

**Comment by masayuki2009** [comment]
> @masayuki2009 please associate your github account with apache account:
> https://whimsy.apache.org/roster/ppmc/nuttx
> so I can add you to reviewer list.

@xiaoxiang781216 I'll setup it later.

**Comment by masayuki2009** [comment]
@xiaoxiang781216 I've just added my github account info to the apache.

**Comment by yamt** [comment]
macOS doesn't have flock.
how about using shlock instead? macOS has it.

**Comment by xiaoxiang781216** [comment]
> macOS doesn't have flock.
> how about using shlock instead? macOS has it.

But shlock doesn't exist on cygwin and msys2, even Ubuntu need install manually with apt-get install:(.

**Comment by xiaoxiang781216** [comment]
How about https://github.com/discoteq/flock:
brew tap discoteq/discoteq
brew install flock

**Comment by masayuki2009** [comment]
@xiaoxiang781216 It looks good to me.

**Comment by patacongo** [comment]
> 
> 
> How about https://github.com/discoteq/flock:
> brew tap discoteq/discoteq
> brew install flock

This would need to be documented so macOS users would have to install flock?  I will merge this PR when the documentation updates are in place.  This should be covered in the top-level README.txt file.

**Comment by xiaoxiang781216** [comment]
@patacongo here is the patch updating README.txt:
https://github.com/apache/incubator-nuttx/pull/337

**Comment by masayuki2009** [comment]
Hi, @xiaoxiang781216,

I found that this solution still has a problem.
Because .arlock files are created in each application directory.

I think the lock file should be in the same directory as '*.a' file, 
because we want to protect '*.a' file access.

Or as I tried before, the lock file could be at the top directory. (rather giant lock)

**Comment by xiaoxiang781216** [comment]
> Hi, @xiaoxiang781216,
> 
> I found that this solution still has a problem.
> Because .arlock files are created in each application directory.
> 
> I think the lock file should be in the same directory as '_.a' file, because we want to protect '_.a' file access.
> 
> Or as I tried before, the lock file could be at the top directory. (rather giant lock)

Yes, I will send a new PR fix this issue.

**Comment by xiaoxiang781216** [comment]
@masayuki2009 see this:
https://github.com/apache/incubator-nuttx-apps/pull/80

**Pull request merged**
