### PR TITLE
Fix echo NULL character correctly

### PR DESCRIPTION
**Pull request by xiaoxiang781216**

### CODE REVIEW

**Comment by yamt** [comment]
it isn't clear to me why you reverted the change.

**Comment by xiaoxiang781216** [comment]
> it isn't clear to me why you reverted the change.

This patch add -f option to force write back null char, but I think that the correct behaviour should always write back all recevie char, do you think so?

image

**Comment by yamt** [comment]
maybe. i don't know what was the motivation of the -f option.

**Comment by yamt** [comment]
@Ouss4 @lukegluke does this change solve what you wanted to solve with the -f option?

**Comment by xiaoxiang781216** [comment]
> maybe. i don't know what was the motivation of the -f option.

Yes, that's why I remove -f option, writing back what cu receive from serial is always a good action. no any reason don't enable it by default.

**Comment by Ouss4** [comment]
I just created the PR on behalf of Oleg, I had nothing to do with the change itself.
@xiaoxiang781216  the old commit sends back everything without any special treatment, even for commands (with ~), was that not desirable?

**Comment by lukegluke** [comment]
Hi @xiaoxiang781216 

Sorry for late reply, for some reason github do not inform me about discussion!
I totally agree that writing back what cu receive from serial is always a good action, and I was surprised why it is not default.
But -f option is **not only** to force write back null char! @Ouss4 is right with -f option cu doesn't stop on escape characters ~.

**Comment by xiaoxiang781216** [comment]
@lukegluke thanks for explanation, I can understand -f option now. I will close my PR without merge.

**Comment by lukegluke** [comment]
@xiaoxiang781216, but I think https://github.com/apache/incubator-nuttx-apps/pull/176/commits/f00bca3250698da686def67a9a60060e254f2fa6 should be merged to always write back all recevied chars even without -f option

**Comment by xiaoxiang781216** [comment]
@lukegluke Ok, I will bring back this patch.

**Comment by Ouss4** [comment]
@yamt If you are good with the change please merge.
(Please Rebase and merge to not create a merge commit).

**Comment by yamt** [comment]
lgtm

**Pull request merged**
