### PR TITLE
Make.defs: Make the lock file in the same location as library file

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Fix the issue note:
https://github.com/apache/incubator-nuttx-apps/pull/80

**Comment by patacongo** [comment]
Need to resolve conflicts

**Comment by xiaoxiang781216** [comment]
> Need to resolve conflicts

Don't need this patch anymore since you select one step archieve approach:
https://github.com/apache/incubator-nuttx-apps/pull/83

**Comment by xiaoxiang781216** [comment]
We need apply this patch again since this patch is revert:
https://github.com/apache/incubator-nuttx-apps/pull/86

**Pull request closed without merging**
