### PR TITLE
lvgl: add button, keypad, lcd interface.

### PR DESCRIPTION
**Pull request by FASTSHIFT**
## Summary
lvgl: add button, keypad, lcd interface.
## Impact
let lvgl access button and lcd devices.
## Testing
daily test

### CODE REVIEW

**Comment by v01d** [comment]
I think that this code should be part of lvgldemo and no lvgl, since this part is usually very dependant on how the application is structured (specific LCD, how is input going to be handled, either event-based or polling, etc). On lvgldemo there's an fb interface, so the LCD interface could be made into a choice (either FB or LCD).

**Comment by xiaoxiang781216** [comment]
> I think that this code should be part of lvgldemo and no lvgl, since this part is usually very dependant on how the application is structured (specific LCD, how is input going to be handled, either event-based or polling, etc). On lvgldemo there's an fb interface, so the LCD interface could be made into a choice (either FB or LCD).

But we can achieve the customization through Kconfig, there isn't technical reason to block us creating the generic and flexible lvgl adapter for NuttX driver.

**Comment by v01d** [comment]
I'm not sure how easy would be to make this generic, since the display driver will usually require supplying the "set pixel" and "rounder" callbacks depending on the particular display to use. As long as it can be disabled I think it is OK.
In that case I think we should move the framebuffer interface (and also made optional) from lvgldemo to here.

**Comment by xiaoxiang781216** [comment]
Let's close it now. the new drivers for v8 will provide later.

**Pull request closed without merging**
