### PR TITLE
nshlib: Disable mb, mh, and mw by default

### PR DESCRIPTION
**Pull request by swkim101**
## Summary

- Fix https://github.com/apache/incubator-nuttx/issues/3011

## Testing

image

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@swkim101 you need remove all CONFIG_NSH_DISABLE_M[B|H|W]=y from nuttx/boards/ to fix the error reported here:
https://github.com/apache/incubator-nuttx-apps/pull/647/checks?check_run_id=2258212861

**Comment by Ouss4** [comment]
> @swkim101 you need remove all CONFIG_NSH_DISABLE_M[B|H|W]=y from nuttx/boards/ to fix the error reported here:
> https://github.com/apache/incubator-nuttx-apps/pull/647/checks?check_run_id=2258212861

There is this PR https://github.com/apache/incubator-nuttx/pull/3240, but it looks like it addresses only NSH configs.

**Comment by btashton** [comment]
That PR does the opposite it need to remove all the explicit disables since this PR makes it the default

**Comment by Ouss4** [comment]
> That PR does the opposite it need to remove all the explicit disables since this PR makes it the default

Ah you're right, I spoke too fast.

**Comment by xiaoxiang781216** [comment]
The change is minor, and the dependence was merged. Let's merge it directly to save the build resource.

**Comment by v01d** [comment]
@xiaoxiang781216 as @btashton mentioned, the Kconfig change is backwards to the intent of the PR. I don't think this should have been merged.

Also, I see quite a few issues such as:
```
< CONFIG_NSH_DISABLE_MB=y
< CONFIG_NSH_DISABLE_MH=y
63d60
< CONFIG_NSH_DISABLE_MW=y
```
in CI.

Let's try not to make a habit of skipping CI (it is now quite faster and less wasteful when pushing again) as we will loose unexpected errors.

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 as @btashton mentioned, the Kconfig change is backwards to the intent of the PR. I don't think this should have been merged.
> 

This patch is needed to make the default option more safer.

> Also, I see quite a few issues such as:
> 
> ```
> < CONFIG_NSH_DISABLE_MB=y
> < CONFIG_NSH_DISABLE_MH=y
> 63d60
> < CONFIG_NSH_DISABLE_MW=y
> ```
> 

It's strange that I can't find these words in the latest nuttx when I want to fix the issue.

> in CI.
> 
> Let's try not to make a habit of skipping CI (it is now quite faster and less wasteful when pushing again) as we will loose unexpected errors.

Ok.

**Comment by btashton** [comment]
The os repo PR was updated to just remove these entries instead of add them which is what we needed, any CI issue should have just been a matter of the order they were merged. 

But yeah generally I agree we should wait on CI. Sometimes I merge if it's obvious not going to have an issue and I'm trying to unblock things.

**Pull request merged**
