### PR TITLE
Remove unused BUILTIN_PROXY_STACKSIZE config

### PR DESCRIPTION
**Pull request by yamt**
It has been unused since the following change:
"All argv types should be char * const * not const char **"

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@yamt could you provide a patch for nuttx to remove all CONFIG_BUILTIN_PROXY_STACKSIZE in nuttx repo?

**Comment by yamt** [comment]
@xiaoxiang781216
is there an easy way to update a bunch of defconfigs?
i mean easier than awk/sed/vi/etc

**Comment by xiaoxiang781216** [comment]
run this command:
tools/refresh.sh --silent all
but some windows specific config need to bypass.

**Comment by yamt** [comment]
thank you. i'll try it later.

**Comment by yamt** [comment]
done https://github.com/apache/incubator-nuttx/pull/267

**Pull request merged**
