### PR TITLE
testing/ltp: split the ltp source include to 2 part

### PR DESCRIPTION
**Pull request by ttnie**
Signed-off-by: nietingting <nietingting@xiaomi.com>

## Summary
testing/ltp: split the ltp source include to 2 part

## Impact
no

## Testing
test on local

### CODE REVIEW

**Comment by btashton** [comment]
Why not just make the underlying build infrastructure support longer lists of files which is what I did.

**Comment by v01d** [comment]
I agree, it is better to fix the underlying problem. This can occur again with other projects.

**Comment by btashton** [comment]
I will submit a PR that uses a max args function split the calls for clean and archive. That way they are chunked on  20 files or something reasonable.

**Comment by v01d** [comment]
Great, I was going to suggest that. That way we can still have some efficiency when this problem does not occur.

**Comment by btashton** [comment]
This should be resolved with this https://github.com/apache/incubator-nuttx/pull/3510

**Comment by xiaoxiang781216** [comment]
Ok, let's close this PR.

**Pull request closed without merging**
