### PR TITLE
apps/Application.mk: fix compile assmbely error

### PR DESCRIPTION
**Pull request by GUIDINGLI**
## Summary

apps/Application.mk: fix compile assmbely error

## Impact

Compile error:
When compile some of *.S file in apps, the compiler only compile first .S file, not all of them.

Reason:
In Application.mk
$(AOBJS): %$(SUFFIX)$(OBJEXT): $(ASRCS)
       $(if $(and $(CONFIG_BUILD_LOADABLE),$(AELFFLAGS)), \
               $(call ELFASSEMBLE, $<, $@), $(call ASSEMBLE, $<, $@))

The $(ASRCS) is the unit of *.s *.S.
But '$<' can't pick each member in $(ASRCS), should use like $(firstword, xx) and $(filter-out, $(firstword)) ...

Resolve:
The simplest solution is devide the .s & .S compile. (See  the patch detail)

### CODE REVIEW

**Comment by davids5** [comment]
@GUIDINGLI We need you help. Please fill out the Description on this and all future PRs. Give an example of the error and the method for testing.

**Comment by GUIDINGLI** [comment]
@davids5 done

**Comment by davids5** [comment]
@GUIDINGLI - Thank you.

**Review by Ouss4 — APPROVED** [review]
LGTM

**Pull request merged**
