### PR TITLE
quickjs: Don't define __NuttX__ manually

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary
Since nuttx/tools/Config.mk will do it for us: https://github.com/apache/incubator-nuttx/pull/2192

## Impact
No functional change

### CODE REVIEW

**Review by davids5 — COMMENTED** [review]
Why mixed case and not __NUTTX__?
presidents:
```
Linux and Linux-derived           __linux__
Android                           __ANDROID__ (implies __linux__)
Linux (non-Android)               __linux__ && !__ANDROID__
Darwin (Mac OS X and iOS)         __APPLE__
Akaros (http://akaros.org)        __ros__
Windows                           _WIN32
Windows 64 bit                    _WIN64 (implies _WIN32)
NaCL                              __native_client__
AsmJS                             __asmjs__
Fuschia                           __Fuchsia__
```

**Comment by btashton** [comment]
It's been `__NuttX__` for a long time in the OS and I believe in buildroot so hard to change.

**Review by btashton — APPROVED** [review]
LGTM

**Comment by xiaoxiang781216** [comment]
@davids5 ```__NuttX__``` isn't invented by quickjs porting, which just follow other library practice(e.g. libc++).  It's hard to change this macro now, because all place library and toolchain refernce it.

**Comment by jerpelea** [comment]
LGTM

**Pull request merged**
