### PR TITLE
nsh/script: support rc.sysinit script

### PR DESCRIPTION
**Pull request by Donny9**
## Summary
Follow: http://glennastory.net/boot/sysinit.html

This is first script that init runs is rc.sysinit. This
script does serval initialization tasks about basic service.

The boot sequence currently provided to the board level is:
```
board_earlyinitialize->
    board_lateinitialize(Peripherals driver, core driver, ...)->
	run rcS script(mount fs, run service) ->
	       board_appinitialize->
```

After this patch:
The boot sequence currently provided to the board level is:
```
board_earlyinitialize->
    board_lateinitialize(core driver,...)->
	run rc.sysinit script(mount fs, run core service) ->
	        board_appinitialize(Peripherals driver)->
		       run rcS script(run other service)->
```
So, Peripheral drivers can do more with the file system and core services.

Signed-off-by: Jiuzhu Dong <dongjiuzhu1@xiaomi.com>

## Impact
Support peripheral drivers can do more with the file system and core services.
## Testing
Ci

### CODE REVIEW

**Comment by pkarashchenko** [comment]
This PR changes the init order, so I support that couple of existing configurations have to be updated:
```
nuttx$ find . -name rcS
./boards/sim/sim/sim/src/etc/init.d/rcS
./boards/risc-v/qemu-rv/rv-virt/src/etc/init.d/rcS
./boards/risc-v/esp32c3/esp32c3-devkit/src/etc/init.d/rcS
```
I mean that we need to rework configs that use rcS as behavior will change. For example description states that after this change `run rc.sysinit script(mount fs, run core service)` and `boards/risc-v/esp32c3/esp32c3-devkit/src/etc/init.d/rcS` contains:
```
/* Create a RAMDISK and mount it at /tmp */

mkrd -m CONFIG_NSH_FATDEVNO -s CONFIG_NSH_FATSECTSIZE CONFIG_NSH_FATNSECTORS
mkfatfs CONCAT(/dev/ram, CONFIG_NSH_FATDEVNO)
mount -t vfat CONCAT(/dev/ram, CONFIG_NSH_FATDEVNO) CONFIG_NSH_FATMOUNTPT
```
So according to new description the mount part of `boards/risc-v/esp32c3/esp32c3-devkit/src/etc/init.d/rcS` should be moved to `boards/risc-v/esp32c3/esp32c3-devkit/src/etc/init.d/rc.sysinit`. The same for other.

**Comment by pkarashchenko** [comment]
Also
```
config NSH_ROMFSETC
	bool "Support ROMFS start-up script"
	default n
	depends on FS_ROMFS
	---help---
		Mount a ROMFS filesystem at /etc and provide a startup script
		at /etc/init.d/rcS.  The default startup script will mount
		a FAT FS RAMDISK at /tmp but the logic is easily extensible.
```
So according to new flow mounting should be done in `rc.sysinit`, so we need to update description for `rcS`

**Comment by pkarashchenko** [comment]
We need to update `Default Start-Up Behavior` in `README.md` to reflect a new flow

**Comment by Donny9** [comment]
> This PR changes the init order, so I support that couple of existing configurations have to be updated:
> 
> ```
> nuttx$ find . -name rcS
> ./boards/sim/sim/sim/src/etc/init.d/rcS
> ./boards/risc-v/qemu-rv/rv-virt/src/etc/init.d/rcS
> ./boards/risc-v/esp32c3/esp32c3-devkit/src/etc/init.d/rcS
> ```
> 
> I mean that we need to rework configs that use rcS as behavior will change. For example description states that after this change `run rc.sysinit script(mount fs, run core service)` and `boards/risc-v/esp32c3/esp32c3-devkit/src/etc/init.d/rcS` contains:
> 
> ```
> /* Create a RAMDISK and mount it at /tmp */
> 
> mkrd -m CONFIG_NSH_FATDEVNO -s CONFIG_NSH_FATSECTSIZE CONFIG_NSH_FATNSECTORS
> mkfatfs CONCAT(/dev/ram, CONFIG_NSH_FATDEVNO)
> mount -t vfat CONCAT(/dev/ram, CONFIG_NSH_FATDEVNO) CONFIG_NSH_FATMOUNTPT
> ```
> 
> So according to new description the mount part of `boards/risc-v/esp32c3/esp32c3-devkit/src/etc/init.d/rcS` should be moved to `boards/risc-v/esp32c3/esp32c3-devkit/src/etc/init.d/rc.sysinit`. The same for other.

Done.

**Comment by Donny9** [comment]
> We need to update `Default Start-Up Behavior` in `README.md` to reflect a new flow

Done!

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by pkarashchenko — APPROVED** [review]

**Pull request merged**
